#!/usr/bin/env python3
"""Generate the docs that must never drift from the code.

docs/VALIDATION.md and docs/REFERENCES.md are written from the live registry
and the live validation run, so they cannot describe a build that no longer
exists. CI regenerates them and fails if the working tree changes, which makes
a stale table a build error rather than a small lie in a README.

Usage:
    python tools/gen_docs.py            # rewrite the generated docs
    python tools/gen_docs.py --check    # non-zero exit if they are out of date
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from ina_sim import __version__
from ina_sim.physics.ns import load_parameterizations
from ina_sim.references import load_references
from ina_sim.validation.runner import load_anchors, run_validation

REPO_ROOT = Path(__file__).resolve().parents[1]
DOCS = REPO_ROOT / "docs"
BANNER = (
    "<!-- GENERATED BY tools/gen_docs.py - DO NOT EDIT BY HAND. "
    "Run `python tools/gen_docs.py` after changing parameterizations, "
    "anchors or references. -->"
)


def _wrap(text: str) -> str:
    return " ".join(str(text).split())


def validation_doc() -> str:
    report = run_validation()
    anchors = {a["id"]: a for a in load_anchors()}
    params = load_parameterizations()

    lines = [BANNER, "", "# Validation", ""]
    lines.append(
        f"Generated from INA-sim {__version__}. Reproduce with `ina-sim validate`."
    )
    lines.append("")
    lines.append(
        "An anchor is only worth having if it is independent of the numbers it "
        "tests. Checking a polynomial against itself proves nothing, so each "
        "anchor below is a claim made in the source's prose, an ordering the "
        "source asserts, a textbook regime the model must land in, or a "
        "calibration check that published measurements really do fall inside "
        "the uncertainty band this tool advertises."
    )
    lines.append("")
    lines.append(
        f"**Result: {report.n_pass} passed, {report.n_fail} failed, "
        f"{report.n_skip} skipped.**"
    )
    lines.append("")
    lines.append("| anchor | status | result | source |")
    lines.append("|---|---|---|---|")
    for r in report.results:
        lines.append(
            f"| `{r.id}` | {r.status.upper()} | {_wrap(r.detail)} | {r.citation} |"
        )
    lines.append("")
    lines.append("## What each anchor is testing")
    lines.append("")
    for r in report.results:
        lines.append(f"### `{r.id}`")
        lines.append("")
        lines.append(_wrap(anchors.get(r.id, {}).get("claim", r.claim)))
        note = anchors.get(r.id, {}).get("note")
        if note:
            lines.append("")
            lines.append(f"*Caveat:* {_wrap(note)}")
        lines.append("")

    lines.append("## Registry under test")
    lines.append("")
    lines.append(
        "| id | material | status | quantity | units | basis | "
        "valid T (°C) | σ (decades) | source |"
    )
    lines.append("|---|---|---|---|---|---|---|---|---|")
    for p in params.values():
        sigma = "assumed 1.0" if p.sigma_log10 is None else f"{p.sigma_log10:g}"
        lines.append(
            f"| `{p.id}` | {p.material} | {p.status} | {p.quantity} | "
            f"`{p.units}` | {p.area_basis} | {p.t_min_c:g} … {p.t_max_c:g} | "
            f"{sigma} | {p.as_dict()['citation']} |"
        )
    lines.append("")
    lines.append(
        "Coverage is deliberately visible: eight parameterizations, of which "
        "seven are published fits and one is derived in-repo and labelled as "
        "such. Materials with no entry return no number."
    )
    lines.append("")
    return "\n".join(lines)


def references_doc() -> str:
    refs = load_references()
    params = load_parameterizations()
    anchors = load_anchors()

    used_by: dict[str, list[str]] = {key: [] for key in refs}
    for p in params.values():
        used_by.setdefault(p.reference, []).append(f"parameterization `{p.id}`")
    for a in anchors:
        used_by.setdefault(a["reference"], []).append(f"anchor `{a['id']}`")

    lines = [BANNER, "", "# References", ""]
    lines.append(
        "Every empirical number in INA-sim traces to an entry here. `access` "
        "records how it entered the repo: **verbatim** (equation transcribed "
        "from the source text), **derived** (computed here from the source's "
        "tabulated measurements, with the script named), or **textbook** "
        "(standard constant or relation)."
    )
    lines.append("")
    lines.append(f"Generated from INA-sim {__version__}. Also available as `ina-sim refs`.")
    lines.append("")
    for key, ref in refs.items():
        lines.append(f"## {ref.short()}")
        lines.append("")
        lines.append(f"`{key}` · access: **{ref.access}** · "
                     f"{'open access' if ref.open_access else 'paywalled'}")
        lines.append("")
        lines.append(ref.citation())
        if ref.url:
            lines.append("")
            lines.append(f"<{ref.url}>")
        lines.append("")
        lines.append(f"**Used for:** {_wrap(ref.note or 'see modules citing this key')}")
        where = used_by.get(key) or []
        if where:
            lines.append("")
            lines.append(f"**Cited by:** {', '.join(sorted(where))}")
        lines.append("")
    return "\n".join(lines)


TARGETS = {
    DOCS / "VALIDATION.md": validation_doc,
    DOCS / "REFERENCES.md": references_doc,
}


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="fail if docs are stale")
    args = ap.parse_args(argv)

    stale: list[str] = []
    for path, build in TARGETS.items():
        content = build()
        if args.check:
            current = path.read_text(encoding="utf-8") if path.exists() else ""
            if current != content:
                stale.append(str(path.relative_to(REPO_ROOT)))
        else:
            path.write_text(content, encoding="utf-8")
            print(f"wrote {path.relative_to(REPO_ROOT)}")

    if args.check:
        if stale:
            print("FAIL: generated docs are out of date:", file=sys.stderr)
            for s in stale:
                print(f"  - {s}", file=sys.stderr)
            print("Run: python tools/gen_docs.py", file=sys.stderr)
            return 1
        print("OK: generated docs are current.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
